from __future__ import annotations


EXTENDED_SOURCE_CATALOG = [
    {
        "source_key": "kiva_us",
        "source_name": "Kiva U.S.",
        "source_kind": "CROWDFUNDING_LENDER",
        "jurisdiction": "NATIONAL",
        "geography": "United States",
        "website": "https://www.kiva.org/borrow",
        "mechanisms": ["ZERO_INTEREST_LOAN", "MICROLOAN", "CROWDFUNDING"],
        "issue_areas": ["small business", "social enterprise", "community development", "workforce"],
        "access_methods": ["WEB", "PORTAL"],
        "nonprofit_fit": "CONDITIONAL",
        "requires_legal_review": False,
        "search_priority": 100,
        "notes": "Evaluate nonprofit or social-enterprise borrower eligibility and real repayment capacity; do not treat as a grant.",
    },
    {
        "source_key": "cdfi_fund_directory",
        "source_name": "U.S. Treasury CDFI Fund Directory",
        "source_kind": "CDFI",
        "jurisdiction": "NATIONAL",
        "geography": "United States",
        "website": "https://www.cdfifund.gov/",
        "mechanisms": ["LOAN", "LOW_INTEREST_LOAN", "COMMUNITY_DEVELOPMENT", "HOUSING", "EQUIPMENT"],
        "issue_areas": ["affordable housing", "community facilities", "economic development", "underserved communities"],
        "access_methods": ["WEB", "SEARCH", "DIRECTORY"],
        "nonprofit_fit": "CONDITIONAL",
        "requires_legal_review": True,
        "search_priority": 100,
    },
    {
        "source_key": "florida_community_loan_fund",
        "source_name": "Florida Community Loan Fund",
        "source_kind": "CDFI",
        "jurisdiction": "STATE",
        "geography": "Florida",
        "website": "https://www.fclf.org/",
        "mechanisms": ["LOAN", "HOUSING", "COMMUNITY_FACILITY", "ECONOMIC_DEVELOPMENT"],
        "issue_areas": ["supportive housing", "affordable housing", "community facilities", "economic development"],
        "access_methods": ["WEB", "BORROWER_INQUIRY"],
        "nonprofit_fit": "DIRECT",
        "requires_legal_review": True,
        "search_priority": 100,
    },
    {
        "source_key": "clearinghouse_cdfi",
        "source_name": "Clearinghouse CDFI",
        "source_kind": "CDFI",
        "jurisdiction": "NATIONAL",
        "geography": "United States",
        "website": "https://www.clearinghousecdfi.com/",
        "mechanisms": ["LOAN", "REAL_ESTATE", "CONSTRUCTION", "COMMUNITY_FACILITY", "SPECIAL_NEEDS_HOUSING"],
        "issue_areas": ["housing", "faith-based facilities", "community development", "nonprofit facilities"],
        "access_methods": ["WEB", "PREAPPLICATION"],
        "nonprofit_fit": "DIRECT",
        "requires_legal_review": True,
        "search_priority": 90,
    },
    {
        "source_key": "fiscal_sponsor_directory",
        "source_name": "National Fiscal Sponsor Search",
        "source_kind": "FISCAL_SPONSOR",
        "jurisdiction": "NATIONAL",
        "geography": "United States",
        "website": "https://www.fiscalsponsors.org/",
        "mechanisms": ["FISCAL_SPONSORSHIP", "GRANT_ACCESS"],
        "issue_areas": ["nonprofit startup", "community projects", "charitable projects"],
        "access_methods": ["WEB", "DIRECTORY", "APPLICATION"],
        "nonprofit_fit": "DIRECT",
        "search_priority": 95,
    },
    {
        "source_key": "pensacola_can_fiscal_sponsor",
        "source_name": "Pensacola Community Action Network Fiscal Sponsorship",
        "source_kind": "FISCAL_SPONSOR",
        "jurisdiction": "LOCAL",
        "geography": "Pensacola, Florida",
        "website": "https://www.pensacolacan.org/",
        "mechanisms": ["FISCAL_SPONSORSHIP", "GRANT_ACCESS", "ADMINISTRATIVE_SUPPORT"],
        "issue_areas": ["community development", "social projects", "Pensacola"],
        "access_methods": ["WEB", "APPLICATION"],
        "nonprofit_fit": "DIRECT",
        "search_priority": 100,
    },
    {
        "source_key": "impact_investor_search",
        "source_name": "Impact Investor and PRI Prospecting",
        "source_kind": "IMPACT_INVESTOR",
        "jurisdiction": "NATIONAL",
        "geography": "United States",
        "mechanisms": ["IMPACT_INVESTMENT", "PRI", "RECOVERABLE_GRANT", "DEBT", "MISSION_INVESTMENT"],
        "issue_areas": ["housing", "reentry", "workforce", "economic mobility", "community development"],
        "access_methods": ["WEB", "SEARCH", "DIRECT_OUTREACH"],
        "nonprofit_fit": "CONDITIONAL",
        "requires_legal_review": True,
        "search_priority": 95,
    },
    {
        "source_key": "angel_network_search",
        "source_name": "Angel and Social Enterprise Investor Prospecting",
        "source_kind": "ANGEL_NETWORK",
        "jurisdiction": "NATIONAL",
        "geography": "United States",
        "mechanisms": ["ANGEL_INVESTMENT", "EQUITY", "CONVERTIBLE", "DEBT"],
        "issue_areas": ["social enterprise", "job creation", "economic development", "mission business"],
        "access_methods": ["WEB", "SEARCH", "DIRECT_OUTREACH"],
        "nonprofit_fit": "INDIRECT",
        "requires_investable_entity": True,
        "requires_legal_review": True,
        "search_priority": 85,
        "notes": "Never offer equity in the charitable nonprofit; route equity to a properly structured social enterprise.",
    },
    {
        "source_key": "corporate_local_giving",
        "source_name": "Corporate Local Giving and Sponsorship Programs",
        "source_kind": "CORPORATE",
        "jurisdiction": "NATIONAL",
        "geography": "United States",
        "mechanisms": ["GRANT", "SPONSORSHIP", "IN_KIND", "EQUIPMENT", "GIFT_CARD"],
        "issue_areas": ["local community", "housing", "workforce", "basic needs", "reentry"],
        "access_methods": ["WEB", "SEARCH", "LOCAL_OUTREACH"],
        "nonprofit_fit": "CONDITIONAL",
        "search_priority": 90,
    },
    {
        "source_key": "community_crowdfunding",
        "source_name": "Community Crowdfunding and Investment Platforms",
        "source_kind": "CROWDFUNDING",
        "jurisdiction": "NATIONAL",
        "geography": "United States",
        "mechanisms": ["CROWDFUNDING", "COMMUNITY_INVESTMENT", "DONATION", "DEBT"],
        "issue_areas": ["small business", "social enterprise", "community projects"],
        "access_methods": ["WEB", "PORTAL"],
        "nonprofit_fit": "CONDITIONAL",
        "requires_legal_review": True,
        "search_priority": 85,
    },
]
