from __future__ import annotations


INVESTOR_SOURCE_CATALOG = [
    {
        "source_key": "giin_members",
        "source_name": "Global Impact Investing Network Members",
        "source_kind": "IMPACT_INVESTOR",
        "jurisdiction": "GLOBAL",
        "geography": "Global",
        "website": "https://thegiin.org/members/",
        "mechanisms": ["IMPACT_INVESTMENT", "DEBT", "EQUITY", "MISSION_INVESTMENT"],
        "issue_areas": ["housing", "community development", "economic mobility", "workforce", "social impact"],
        "access_methods": ["WEB", "DIRECTORY", "DIRECT_OUTREACH"],
        "nonprofit_fit": "CONDITIONAL",
        "requires_legal_review": True,
        "search_priority": 88,
        "notes": "Prospecting directory. Verify each investor's geography, sector, instrument, minimum check size, and applicant structure before outreach.",
    },
    {
        "source_key": "mission_investors_exchange",
        "source_name": "Mission Investors Exchange",
        "source_kind": "PHILANTHROPIC_INVESTOR",
        "jurisdiction": "NATIONAL",
        "geography": "United States",
        "website": "https://missioninvestors.org/tools/search/mission-investment-database",
        "mechanisms": ["PRI", "MRI", "RECOVERABLE_CAPITAL", "DEBT", "MISSION_INVESTMENT"],
        "issue_areas": ["program related investment", "housing", "community development", "social entrepreneurs", "place-based investing"],
        "access_methods": ["WEB", "DATABASE", "PROSPECTING"],
        "nonprofit_fit": "CONDITIONAL",
        "requires_legal_review": True,
        "search_priority": 95,
        "notes": "Use to identify foundations and mission investors with PRI/MRI history; individual funder eligibility still requires verification.",
    },
    {
        "source_key": "angel_capital_association",
        "source_name": "Angel Capital Association Member Directory",
        "source_kind": "ANGEL_NETWORK",
        "jurisdiction": "NATIONAL",
        "geography": "United States",
        "website": "https://angelcapitalassociation.org/",
        "mechanisms": ["ANGEL_INVESTMENT", "EQUITY", "CONVERTIBLE", "DEBT"],
        "issue_areas": ["startup", "social enterprise", "job creation", "economic development"],
        "access_methods": ["WEB", "MEMBER_DIRECTORY", "DIRECT_OUTREACH"],
        "nonprofit_fit": "INDIRECT",
        "requires_investable_entity": True,
        "requires_legal_review": True,
        "search_priority": 82,
        "notes": "For a separate investable social-enterprise entity only; never offer equity in the charitable nonprofit.",
    },
    {
        "source_key": "florida_funders",
        "source_name": "Florida Funders",
        "source_kind": "ANGEL_NETWORK",
        "jurisdiction": "STATE",
        "geography": "Florida",
        "website": "https://www.floridafunders.com/",
        "mechanisms": ["VENTURE_CAPITAL", "ANGEL_INVESTMENT", "EQUITY"],
        "issue_areas": ["early-stage technology", "innovation", "job creation"],
        "access_methods": ["WEB", "FOUNDER_OUTREACH"],
        "nonprofit_fit": "INDIRECT",
        "requires_investable_entity": True,
        "requires_legal_review": True,
        "search_priority": 55,
        "notes": "Primarily early-stage technology companies; treat as a future social-enterprise prospect, not direct nonprofit funding.",
    },
]
