from __future__ import annotations

from enum import Enum


class Jurisdiction(str, Enum):
    FEDERAL = "FEDERAL"
    STATE = "STATE"
    COUNTY = "COUNTY"
    CITY = "CITY"
    MUNICIPAL = "MUNICIPAL"
    REGIONAL = "REGIONAL"
    LOCAL = "LOCAL"
    NATIONAL = "NATIONAL"
    PRIVATE = "PRIVATE"
    INTERNATIONAL = "INTERNATIONAL"


class SourceKind(str, Enum):
    GOVERNMENT = "GOVERNMENT"
    FOUNDATION = "FOUNDATION"
    COMMUNITY_FOUNDATION = "COMMUNITY_FOUNDATION"
    FAMILY_FOUNDATION = "FAMILY_FOUNDATION"
    CORPORATE = "CORPORATE"
    BANK = "BANK"
    CDFI = "CDFI"
    FAITH_BASED = "FAITH_BASED"
    CHURCH = "CHURCH"
    ANGEL_NETWORK = "ANGEL_NETWORK"
    ANGEL_INVESTOR = "ANGEL_INVESTOR"
    IMPACT_INVESTOR = "IMPACT_INVESTOR"
    IMPACT_FUND = "IMPACT_FUND"
    PHILANTHROPIC_INVESTOR = "PHILANTHROPIC_INVESTOR"
    COMMUNITY_REDEVELOPMENT = "COMMUNITY_REDEVELOPMENT"
    CONTINUUM_OF_CARE = "CONTINUUM_OF_CARE"
    WORKFORCE_BOARD = "WORKFORCE_BOARD"
    ECONOMIC_DEVELOPMENT = "ECONOMIC_DEVELOPMENT"
    SPONSOR = "SPONSOR"
    OTHER = "OTHER"


class FundingMechanism(str, Enum):
    GRANT = "GRANT"
    GENERAL_OPERATING = "GENERAL_OPERATING"
    PROGRAM_GRANT = "PROGRAM_GRANT"
    CAPITAL_GRANT = "CAPITAL_GRANT"
    CONSTRUCTION = "CONSTRUCTION"
    LAND_PROPERTY = "LAND_PROPERTY"
    EQUIPMENT = "EQUIPMENT"
    HOUSING = "HOUSING"
    REENTRY = "REENTRY"
    HOMELESSNESS = "HOMELESSNESS"
    WORKFORCE = "WORKFORCE"
    COMMUNITY_DEVELOPMENT = "COMMUNITY_DEVELOPMENT"
    ECONOMIC_DEVELOPMENT = "ECONOMIC_DEVELOPMENT"
    MATCHING_GRANT = "MATCHING_GRANT"
    CHALLENGE_GRANT = "CHALLENGE_GRANT"
    SPONSORSHIP = "SPONSORSHIP"
    IN_KIND = "IN_KIND"
    PROGRAM_RELATED_INVESTMENT = "PROGRAM_RELATED_INVESTMENT"
    IMPACT_INVESTMENT = "IMPACT_INVESTMENT"
    EQUITY_INVESTMENT = "EQUITY_INVESTMENT"
    RECOVERABLE_GRANT = "RECOVERABLE_GRANT"
    FORGIVABLE_FINANCING = "FORGIVABLE_FINANCING"
    LOW_INTEREST_LOAN = "LOW_INTEREST_LOAN"
    LOAN = "LOAN"
    TAX_CREDIT = "TAX_CREDIT"
    CONTRACT = "CONTRACT"
    PROCUREMENT = "PROCUREMENT"
    DONATION = "DONATION"
    OTHER = "OTHER"


class NonprofitFit(str, Enum):
    DIRECT = "DIRECT"
    CONDITIONAL = "CONDITIONAL"
    INDIRECT = "INDIRECT"
    NOT_APPLICABLE = "NOT_APPLICABLE"


class AccessMethod(str, Enum):
    API = "API"
    WEB = "WEB"
    SEARCH = "SEARCH"
    FEED = "FEED"
    EMAIL = "EMAIL"
    PORTAL = "PORTAL"
    MANUAL = "MANUAL"
    PARTNER_REFERRAL = "PARTNER_REFERRAL"
